"""
Compliance report generator - Creates compliance reports in HTML and JSON formats.
"""

import json
import html as _html
from datetime import datetime


class ComplianceReportGenerator:
    """Generates compliance reports for CIS Docker Benchmark and ISO/IEC 27001."""

    def __init__(self, compliance_findings, audit_target="All Containers"):
        self.compliance_findings = compliance_findings
        self.generated_at = datetime.now().isoformat()
        self.audit_target = audit_target

    # Public API

    def to_json(self, pretty=True):
        report = {
            "metadata": {
                "generated_at": self.generated_at,
                "audit_target": self.audit_target,
                "report_type": "Compliance - CIS Docker Benchmark vs ISO/IEC 27001"
            },
            "summary": self._generate_summary(),
            "findings": self.compliance_findings,
            "analysis": {
                "by_severity": self._group_by_severity(),
                "by_category": self._group_by_category(),
                "iso_coverage": self._analyze_iso_coverage()
            }
        }
        return json.dumps(report, indent=2 if pretty else None, ensure_ascii=False)

    def to_html(self, title="DockAudit-SCA Compliance Report"):
        summary = self._generate_summary()
        by_category = self._group_by_category()
        iso_coverage = self._analyze_iso_coverage()
        categories = sorted(set(f.get("category", "General") for f in self.compliance_findings))

        generated_short = self.generated_at.replace("T", " ")[:19]

        parts = [
            "<!DOCTYPE html>",
            '<html lang="es">',
            "<head>",
            '  <meta charset="UTF-8">',
            '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
            f"  <title>{_html.escape(title)}</title>",
            '  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>',
            "  <style>",
            self._css(),
            "  </style>",
            "</head>",
            "<body>",
            '<div class="container">',
            self._html_header(),
            '<div class="metadata-bar">',
            f'  <span><strong>Target:</strong> {_html.escape(self.audit_target)}</span>',
            f'  <span><strong>Generated:</strong> {generated_short}</span>',
            '  <span><strong>Standard:</strong> CIS Docker Benchmark 1.6 &mdash; ISO/IEC 27001:2022</span>',
            '</div>',
            self._html_summary_section(summary),
            self._html_filter_bar(categories),
            self._html_findings_table(),
            self._html_category_chart(by_category),
            self._html_iso_table(iso_coverage),
            "<footer>",
            "  <p>Generated by <strong>DockAudit-SCA</strong> &mdash; Security Audit &amp; Compliance Tool</p>",
            "</footer>",
            "</div>",
            "<script>",
            self._js(summary),
            "</script>",
            "</body>",
            "</html>",
        ]
        return "\n".join(parts)

    # CSS

    def _css(self):
        return """
:root {
    --primary: #1a365d;
    --primary-light: #2c5282;
    --accent: #3182ce;
    --compliant-bg: #c6f6d5;
    --compliant-text: #22543d;
    --compliant-border: #276749;
    --noncompliant-bg: #fed7d7;
    --noncompliant-text: #822727;
    --noncompliant-border: #c53030;
    --unknown-bg: #feebc8;
    --unknown-text: #7b341e;
    --unknown-border: #c05621;
    --severity-critical: #742a2a;
    --severity-high: #c05621;
    --severity-medium: #975a16;
    --severity-low: #276749;
    --bg: #f7fafc;
    --surface: #ffffff;
    --border: #e2e8f0;
    --text: #2d3748;
    --text-muted: #718096;
    --shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08);
    --shadow-md: 0 4px 6px rgba(0,0,0,0.1), 0 2px 4px rgba(0,0,0,0.06);
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.6;
    font-size: 14px;
}
.container { max-width: 1280px; margin: 0 auto; padding: 20px; }

/* Header */
header {
    background: linear-gradient(135deg, var(--primary) 0%, var(--primary-light) 100%);
    color: white;
    padding: 28px 36px;
    border-radius: 8px 8px 0 0;
    box-shadow: var(--shadow-md);
    display: flex;
    align-items: center;
    gap: 16px;
}
.header-icon { font-size: 2.2em; }
header h1 { font-size: 1.9em; font-weight: 700; letter-spacing: -0.5px; }
header p { opacity: 0.75; font-size: 0.88em; margin-top: 3px; }

/* Metadata bar */
.metadata-bar {
    background: var(--primary-light);
    color: rgba(255,255,255,0.88);
    padding: 9px 36px;
    display: flex;
    gap: 36px;
    font-size: 0.82em;
    border-radius: 0 0 8px 8px;
    margin-bottom: 24px;
    flex-wrap: wrap;
}

/* Summary grid */
.summary-grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr 260px;
    gap: 14px;
    margin-bottom: 20px;
    align-items: stretch;
}
.stat-card {
    background: var(--surface);
    border-radius: 8px;
    padding: 18px 16px;
    box-shadow: var(--shadow);
    border-top: 4px solid var(--border);
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 4px;
}
.stat-card.card-total    { border-top-color: var(--accent); }
.stat-card.card-compliant    { border-top-color: var(--compliant-border); }
.stat-card.card-noncompliant { border-top-color: var(--noncompliant-border); }
.stat-card.card-unknown      { border-top-color: var(--unknown-border); }
.stat-card.card-rate         { border-top-color: var(--primary); }
.stat-number { font-size: 2.2em; font-weight: 700; line-height: 1; }
.stat-card.card-total        .stat-number { color: var(--accent); }
.stat-card.card-compliant    .stat-number { color: var(--compliant-border); }
.stat-card.card-noncompliant .stat-number { color: var(--noncompliant-border); }
.stat-card.card-unknown      .stat-number { color: var(--unknown-border); }
.stat-card.card-rate         .stat-number { color: var(--primary); }
.stat-label {
    font-size: 0.72em;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: var(--text-muted);
    font-weight: 600;
}
.chart-card {
    background: var(--surface);
    border-radius: 8px;
    padding: 12px;
    box-shadow: var(--shadow);
    display: flex;
    align-items: center;
    justify-content: center;
}

/* Section */
.section {
    background: var(--surface);
    border-radius: 8px;
    padding: 22px 24px;
    margin-bottom: 20px;
    box-shadow: var(--shadow);
}
.section-header {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    margin-bottom: 14px;
    padding-bottom: 10px;
    border-bottom: 2px solid var(--border);
}
.section-title { font-size: 1.0em; font-weight: 700; color: var(--primary); }
.section-subtitle { font-size: 0.82em; color: var(--text-muted); margin-top: 2px; }

/* Filter bar */
.filter-bar {
    background: var(--surface);
    border-radius: 8px;
    padding: 13px 18px;
    margin-bottom: 14px;
    box-shadow: var(--shadow);
    display: flex;
    gap: 10px;
    align-items: center;
    flex-wrap: wrap;
}
.filter-bar label {
    font-size: 0.75em;
    font-weight: 600;
    color: var(--text-muted);
    text-transform: uppercase;
    letter-spacing: 0.5px;
    white-space: nowrap;
}
.filter-bar select, .filter-bar input[type="text"] {
    padding: 5px 9px;
    border: 1px solid var(--border);
    border-radius: 4px;
    font-size: 0.85em;
    color: var(--text);
    background: var(--bg);
    outline: none;
}
.filter-bar select:focus, .filter-bar input:focus { border-color: var(--accent); }
.filter-bar input[type="text"] { min-width: 180px; }
.filter-count { margin-left: auto; font-size: 0.82em; color: var(--text-muted); white-space: nowrap; }
.btn-sm {
    padding: 5px 11px;
    border: 1px solid var(--border);
    border-radius: 4px;
    background: var(--bg);
    color: var(--text);
    font-size: 0.8em;
    cursor: pointer;
    font-weight: 500;
}
.btn-sm:hover { background: var(--border); }

/* Findings table */
table { width: 100%; border-collapse: collapse; font-size: 0.88em; }
thead tr { background: var(--bg); }
th {
    padding: 9px 12px;
    text-align: left;
    font-weight: 600;
    font-size: 0.78em;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-muted);
    border-bottom: 2px solid var(--border);
    white-space: nowrap;
}
td { padding: 9px 12px; border-bottom: 1px solid var(--border); vertical-align: middle; }
tr.finding-row { cursor: pointer; transition: background 0.1s; }
tr.finding-row:hover { background: #edf2f7; }

/* Expand button */
.expand-btn {
    background: none;
    border: 1px solid var(--border);
    border-radius: 4px;
    width: 24px;
    height: 24px;
    cursor: pointer;
    font-size: 0.7em;
    color: var(--text-muted);
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.15s;
    flex-shrink: 0;
}
.expand-btn:hover { background: #ebf8ff; color: var(--accent); border-color: var(--accent); }
.expand-btn.expanded { color: var(--accent); border-color: var(--accent); background: #ebf8ff; }

/* Detail row */
.detail-row td {
    background: #f8fafc;
    padding: 0;
    border-bottom: 2px solid var(--border);
}
.detail-content {
    padding: 18px 24px;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 18px;
}
.detail-block h4 {
    font-size: 0.75em;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-muted);
    margin-bottom: 7px;
    font-weight: 700;
}
.detail-block p { font-size: 0.88em; color: var(--text); line-height: 1.5; }
.detail-block.full-width { grid-column: 1 / -1; }
.remediation-box {
    background: #fffbeb;
    border: 1px solid #f6e05e;
    border-left: 4px solid #d69e2e;
    border-radius: 4px;
    padding: 10px 14px;
    font-size: 0.88em;
    line-height: 1.5;
    color: var(--text);
}
.detail-kv { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 6px; }
.kv-item {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 4px;
    padding: 3px 9px;
    font-size: 0.82em;
    font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
}
.kv-key { color: var(--text-muted); }
.kv-val { color: var(--text); font-weight: 600; }
.iso-tags { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 6px; }
.iso-tag {
    background: #ebf4ff;
    border: 1px solid #bee3f8;
    color: #2b6cb0;
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 0.8em;
    font-weight: 600;
}
.iso-tag-domain {
    color: var(--text-muted);
    font-weight: 400;
    margin-left: 5px;
    font-size: 0.9em;
}

/* Status & severity badges */
.badge {
    display: inline-block;
    padding: 2px 9px;
    border-radius: 12px;
    font-size: 0.78em;
    font-weight: 700;
    white-space: nowrap;
    letter-spacing: 0.3px;
}
.badge-compliant     { background: var(--compliant-bg);    color: var(--compliant-text);    border: 1px solid var(--compliant-border); }
.badge-non-compliant { background: var(--noncompliant-bg); color: var(--noncompliant-text); border: 1px solid var(--noncompliant-border); }
.badge-unknown       { background: var(--unknown-bg);      color: var(--unknown-text);      border: 1px solid var(--unknown-border); }
.badge-critical { background: #fff5f5; color: var(--severity-critical); border: 1px solid #feb2b2; }
.badge-high     { background: #fffaf0; color: var(--severity-high);     border: 1px solid #fbd38d; }
.badge-medium   { background: #fffff0; color: var(--severity-medium);   border: 1px solid #faf089; }
.badge-low      { background: #f0fff4; color: var(--severity-low);      border: 1px solid #9ae6b4; }

/* Category chart */
.category-bars { display: flex; flex-direction: column; gap: 11px; }
.cat-row { display: flex; align-items: center; gap: 12px; }
.cat-label { width: 200px; font-size: 0.84em; font-weight: 500; color: var(--text); flex-shrink: 0; }
.cat-bar-wrap {
    flex: 1;
    background: var(--bg);
    border-radius: 4px;
    height: 22px;
    position: relative;
    overflow: hidden;
    border: 1px solid var(--border);
}
.cat-bar-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--compliant-border) 0%, #48bb78 100%);
    border-radius: 3px;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    padding-right: 8px;
    min-width: 0;
    transition: width 0.4s ease;
}
.cat-bar-fill span { color: white; font-size: 0.76em; font-weight: 700; text-shadow: 0 1px 2px rgba(0,0,0,0.3); }
.cat-stats { width: 110px; font-size: 0.8em; color: var(--text-muted); flex-shrink: 0; text-align: right; }

/* ISO table */
.iso-table-wrap { overflow-x: auto; }
.iso-table-wrap table { min-width: 600px; }

/* Footer */
footer { text-align: center; padding: 22px; color: var(--text-muted); font-size: 0.84em; margin-top: 4px; }

/* Print */
@media print {
    body { background: white; font-size: 11px; }
    .container { padding: 0; max-width: 100%; }
    .filter-bar, .expand-btn { display: none !important; }
    .detail-row { display: table-row !important; }
    .detail-content { padding: 10px; }
    header, .metadata-bar { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .section { box-shadow: none; border: 1px solid #e2e8f0; page-break-inside: avoid; }
    .summary-grid { grid-template-columns: repeat(5, 1fr); }
    .chart-card { display: none; }
    @page { margin: 1.5cm; }
}
"""

    # JavaScript

    def _js(self, summary):
        c = summary['compliant']
        nc = summary['non_compliant']
        u = summary['unknown']
        t = summary['total_controls']
        return f"""
(function() {{
    var ctx = document.getElementById('complianceChart');
    if (!ctx || typeof Chart === 'undefined') return;
    new Chart(ctx, {{
        type: 'doughnut',
        data: {{
            labels: ['Compliant', 'Non-Compliant', 'Unknown'],
            datasets: [{{
                data: [{c}, {nc}, {u}],
                backgroundColor: ['#c6f6d5', '#fed7d7', '#feebc8'],
                borderColor: ['#276749', '#c53030', '#c05621'],
                borderWidth: 2,
                hoverOffset: 4
            }}]
        }},
        options: {{
            responsive: true,
            maintainAspectRatio: false,
            plugins: {{
                legend: {{
                    position: 'bottom',
                    labels: {{ padding: 10, font: {{ size: 11 }} }}
                }},
                tooltip: {{
                    callbacks: {{
                        label: function(ctx) {{
                            var pct = (ctx.raw / {t} * 100).toFixed(1);
                            return ctx.label + ': ' + ctx.raw + ' (' + pct + '%)';
                        }}
                    }}
                }}
            }},
            cutout: '65%'
        }}
    }});
}})();

function toggleRow(btn, event) {{
    if (event) event.stopPropagation();
    var row = btn.closest('tr');
    var detail = row.nextElementSibling;
    if (!detail || !detail.classList.contains('detail-row')) return;
    var hidden = detail.style.display === 'none' || detail.style.display === '';
    detail.style.display = hidden ? 'table-row' : 'none';
    btn.innerHTML = hidden ? '&#9662;' : '&#9656;';
    btn.classList.toggle('expanded', hidden);
}}

document.querySelectorAll('tr.finding-row').forEach(function(row) {{
    row.addEventListener('click', function(e) {{
        if (e.target.classList.contains('expand-btn') || e.target.closest('.expand-btn')) return;
        var btn = row.querySelector('.expand-btn');
        if (btn) toggleRow(btn, null);
    }});
}});

function applyFilters() {{
    var status   = document.getElementById('filterStatus').value;
    var severity = document.getElementById('filterSeverity').value;
    var category = document.getElementById('filterCategory').value;
    var search   = document.getElementById('filterSearch').value.toLowerCase();
    var visible  = 0;
    document.querySelectorAll('tr.finding-row').forEach(function(row) {{
        var show = (
            (!status   || row.dataset.status   === status)   &&
            (!severity || row.dataset.severity === severity) &&
            (!category || row.dataset.category === category) &&
            (!search   || row.textContent.toLowerCase().includes(search))
        );
        row.style.display = show ? '' : 'none';
        var detail = row.nextElementSibling;
        if (detail && detail.classList.contains('detail-row') && !show) {{
            detail.style.display = 'none';
        }}
        if (show) visible++;
    }});
    document.getElementById('visibleCount').textContent = visible;
}}

function expandAll() {{
    document.querySelectorAll('tr.finding-row').forEach(function(row) {{
        if (row.style.display === 'none') return;
        var detail = row.nextElementSibling;
        if (detail && detail.classList.contains('detail-row')) detail.style.display = 'table-row';
        var btn = row.querySelector('.expand-btn');
        if (btn) {{ btn.innerHTML = '&#9662;'; btn.classList.add('expanded'); }}
    }});
}}

function collapseAll() {{
    document.querySelectorAll('tr.detail-row').forEach(function(r) {{ r.style.display = 'none'; }});
    document.querySelectorAll('.expand-btn').forEach(function(b) {{
        b.innerHTML = '&#9656;';
        b.classList.remove('expanded');
    }});
}}
"""

    # HTML sections

    def _html_header(self):
        return (
            '<header>'
            '<span class="header-icon">&#128274;</span>'
            '<div>'
            '<h1>DockAudit-SCA</h1>'
            '<p>CIS Docker Benchmark &amp; ISO/IEC 27001 Compliance Report</p>'
            '</div>'
            '</header>'
        )

    def _html_summary_section(self, summary):
        c = summary['compliant']
        nc = summary['non_compliant']
        u = summary['unknown']
        t = summary['total_controls']
        pct = summary['compliance_percentage']
        return f"""
<div class="summary-grid">
  <div class="stat-card card-total">
    <div class="stat-number">{t}</div>
    <div class="stat-label">Total Controls</div>
  </div>
  <div class="stat-card card-compliant">
    <div class="stat-number">{c}</div>
    <div class="stat-label">Compliant</div>
  </div>
  <div class="stat-card card-noncompliant">
    <div class="stat-number">{nc}</div>
    <div class="stat-label">Non-Compliant</div>
  </div>
  <div class="stat-card card-unknown">
    <div class="stat-number">{u}</div>
    <div class="stat-label">Unknown</div>
  </div>
  <div class="stat-card card-rate">
    <div class="stat-number">{pct:.1f}%</div>
    <div class="stat-label">Compliance Rate</div>
  </div>
  <div class="chart-card">
    <canvas id="complianceChart" width="230" height="190"></canvas>
  </div>
</div>
"""

    def _html_filter_bar(self, categories):
        cat_opts = "".join(
            f'<option value="{_html.escape(c)}">{_html.escape(c)}</option>'
            for c in categories
        )
        total = len(self.compliance_findings)
        return f"""
<div class="filter-bar">
  <label>Status</label>
  <select id="filterStatus" onchange="applyFilters()">
    <option value="">All</option>
    <option value="compliant">Compliant</option>
    <option value="non_compliant">Non-Compliant</option>
    <option value="unknown">Unknown</option>
  </select>
  <label>Severity</label>
  <select id="filterSeverity" onchange="applyFilters()">
    <option value="">All</option>
    <option value="critical">Critical</option>
    <option value="high">High</option>
    <option value="medium">Medium</option>
    <option value="low">Low</option>
  </select>
  <label>Category</label>
  <select id="filterCategory" onchange="applyFilters()">
    <option value="">All</option>
    {cat_opts}
  </select>
  <input type="text" id="filterSearch" placeholder="Search controls..." oninput="applyFilters()">
  <button class="btn-sm" onclick="expandAll()">Expand All</button>
  <button class="btn-sm" onclick="collapseAll()">Collapse All</button>
  <span class="filter-count">Showing <strong id="visibleCount">{total}</strong> of {total}</span>
</div>
"""

    def _html_findings_table(self):
        rows = []
        for finding in self.compliance_findings:
            cis      = _html.escape(finding.get("cis_control", ""))
            title    = _html.escape(finding.get("title", ""))
            category = finding.get("category", "General")
            severity = finding.get("severity", "low")
            status   = finding.get("status", "unknown")

            status_css   = status.replace("_", "-")
            status_label = status.replace("_", " ").title()

            description = _html.escape(finding.get("description") or "No description available.")
            remediation = _html.escape(finding.get("remediation") or "No remediation steps available.")

            details = finding.get("details") or {}
            if details:
                kv_html = "".join(
                    f'<span class="kv-item">'
                    f'<span class="kv-key">{_html.escape(str(k))}:</span> '
                    f'<span class="kv-val">{_html.escape(str(v))}</span>'
                    f'</span>'
                    for k, v in details.items()
                )
                details_html = f'<div class="detail-kv">{kv_html}</div>'
            else:
                details_html = '<p style="color:var(--text-muted);font-size:0.85em;">No additional technical details.</p>'

            iso_controls = finding.get("iso27001_controls") or []
            if iso_controls:
                iso_html = '<div class="iso-tags">' + "".join(
                    f'<span class="iso-tag">{_html.escape(c.get("code",""))}'
                    f'<span class="iso-tag-domain">{_html.escape(c.get("domain",""))}</span>'
                    f'</span>'
                    for c in iso_controls
                ) + '</div>'
            else:
                iso_html = '<span style="color:var(--text-muted);font-size:0.85em;">None mapped</span>'

            cat_esc = _html.escape(category)
            rows.append(f"""
<tr class="finding-row" data-status="{status}" data-severity="{severity}" data-category="{cat_esc}">
  <td><button class="expand-btn" onclick="toggleRow(this, event)" title="Toggle details">&#9656;</button></td>
  <td><strong>{cis}</strong></td>
  <td><span style="font-size:0.82em;color:var(--text-muted)">{cat_esc}</span></td>
  <td>{title}</td>
  <td><span class="badge badge-{severity}">{severity.upper()}</span></td>
  <td><span class="badge badge-{status_css}">{status_label}</span></td>
</tr>
<tr class="detail-row" style="display:none">
  <td colspan="6">
    <div class="detail-content">
      <div class="detail-block">
        <h4>Description</h4>
        <p>{description}</p>
      </div>
      <div class="detail-block">
        <h4>Remediation</h4>
        <div class="remediation-box">{remediation}</div>
      </div>
      <div class="detail-block">
        <h4>Technical Evidence</h4>
        {details_html}
      </div>
      <div class="detail-block">
        <h4>ISO/IEC 27001 Controls</h4>
        {iso_html}
      </div>
    </div>
  </td>
</tr>""")

        rows_html = "\n".join(rows)
        return f"""
<div class="section">
  <div class="section-header">
    <div>
      <div class="section-title">Compliance Findings</div>
      <div class="section-subtitle">Click any row to expand details &mdash; description, remediation steps, technical evidence and ISO 27001 mapping</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th style="width:36px"></th>
        <th style="width:88px">Control</th>
        <th style="width:175px">Category</th>
        <th>Title</th>
        <th style="width:96px">Severity</th>
        <th style="width:128px">Status</th>
      </tr>
    </thead>
    <tbody id="findingsTableBody">
      {rows_html}
    </tbody>
  </table>
</div>
"""

    def _html_category_chart(self, by_category):
        bars = []
        for category, controls in sorted(by_category.items()):
            compliant = sum(1 for c in controls if c["status"] == "compliant")
            total     = len(controls)
            pct       = (compliant / total * 100) if total > 0 else 0
            cat_esc   = _html.escape(category)
            pct_label = f'<span>{pct:.0f}%</span>' if pct >= 12 else ""
            bars.append(f"""
  <div class="cat-row">
    <div class="cat-label">{cat_esc}</div>
    <div class="cat-bar-wrap">
      <div class="cat-bar-fill" style="width:{pct:.1f}%">{pct_label}</div>
    </div>
    <div class="cat-stats">{compliant}/{total} compliant</div>
  </div>""")

        return f"""
<div class="section">
  <div class="section-header">
    <div>
      <div class="section-title">Compliance by CIS Section</div>
      <div class="section-subtitle">Proportion of compliant controls per benchmark section</div>
    </div>
  </div>
  <div class="category-bars">{"".join(bars)}
  </div>
</div>
"""

    def _html_iso_table(self, iso_coverage):
        rows = []
        for domain, data in sorted(iso_coverage.items()):
            total      = data["total"]
            compliant  = data["compliant"]
            nc         = data["non_compliant"]
            u          = data["unknown"]
            coverage   = (compliant / total * 100) if total > 0 else 0
            codes      = ", ".join(sorted(set(data["controls"])))
            rows.append(f"""
  <tr>
    <td>
      <strong>{_html.escape(domain)}</strong><br>
      <span style="font-size:0.8em;color:var(--text-muted)">{_html.escape(codes)}</span>
    </td>
    <td style="text-align:center"><span class="badge badge-compliant">{compliant}</span></td>
    <td style="text-align:center"><span class="badge badge-non-compliant">{nc}</span></td>
    <td style="text-align:center"><span class="badge badge-unknown">{u}</span></td>
    <td style="text-align:center;font-weight:600">{coverage:.1f}%</td>
  </tr>""")

        return f"""
<div class="section">
  <div class="section-header">
    <div>
      <div class="section-title">ISO/IEC 27001:2022 Coverage</div>
      <div class="section-subtitle">Annex A control compliance derived from CIS Docker Benchmark mapping</div>
    </div>
  </div>
  <div class="iso-table-wrap">
    <table>
      <thead>
        <tr>
          <th>Domain</th>
          <th style="text-align:center">Compliant</th>
          <th style="text-align:center">Non-Compliant</th>
          <th style="text-align:center">Unknown</th>
          <th style="text-align:center">Coverage</th>
        </tr>
      </thead>
      <tbody>{"".join(rows)}
      </tbody>
    </table>
  </div>
</div>
"""

    # Data helpers

    def _generate_summary(self):
        total        = len(self.compliance_findings)
        compliant    = sum(1 for f in self.compliance_findings if f["status"] == "compliant")
        non_compliant = sum(1 for f in self.compliance_findings if f["status"] == "non_compliant")
        unknown      = sum(1 for f in self.compliance_findings if f["status"] == "unknown")
        pct          = (compliant / total * 100) if total > 0 else 0
        return {
            "total_controls": total,
            "compliant": compliant,
            "non_compliant": non_compliant,
            "unknown": unknown,
            "compliance_percentage": round(pct, 2)
        }

    def _group_by_severity(self):
        result = {}
        for f in self.compliance_findings:
            sev = f.get("severity", "unknown")
            result.setdefault(sev, []).append(f)
        return result

    def _group_by_category(self):
        result = {}
        for f in self.compliance_findings:
            cat = f.get("category", "General")
            result.setdefault(cat, []).append(f)
        return result

    def _analyze_iso_coverage(self):
        iso_coverage = {}
        for finding in self.compliance_findings:
            for iso in finding.get("iso27001_controls") or []:
                domain = iso.get("domain", "Unknown")
                if domain not in iso_coverage:
                    iso_coverage[domain] = {
                        "total": 0,
                        "compliant": 0,
                        "non_compliant": 0,
                        "unknown": 0,
                        "controls": []
                    }
                iso_coverage[domain]["total"] += 1
                iso_coverage[domain]["controls"].append(iso.get("code", ""))
                status = finding.get("status")
                if status == "compliant":
                    iso_coverage[domain]["compliant"] += 1
                elif status == "non_compliant":
                    iso_coverage[domain]["non_compliant"] += 1
                else:
                    iso_coverage[domain]["unknown"] += 1
        return iso_coverage
